apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  selector:
    app: multi-container-app  # Match the labels of your deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose
      targetPort: 80  # Port your first container listens on
    - protocol: TCP
      port: 8080  # Another port to expose
      targetPort: 8080  # Port your second container listens on
  type: LoadBalancer  # Type of service, change if needed (ClusterIP, NodePort, LoadBalancer)

