apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  selector:
    app: multi-container-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: reddit-clone
spec:
  selector:
    app: reddit-clone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

